version: '3.4'

services:
  worm:
    image: cpp
    container_name: worms
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VARIANT: ubuntu-20.04
    volumes:
      - type: bind
        source: ../
        target: /home/keisuke
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
        read_only: true
    # cap_add: 
    #   - SYS_PTRACE
    privileged: true
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: /home/keisuke