FROM kei0709/ubuntu22.04-cpp:${TARGETARCH}
ARG USERNAME=user
USER ${USERNAME}
COPY python-package.sh python-package.sh
COPY ssh-find-agent/ /home/${USERNAME}/ssh-find-agent/
# RUN cat ssh-find-agent.sh >> $HOME/.bashrc
COPY ssh-bashrc.sh ssh-bashrc.sh
RUN cat ssh-bashrc.sh >> ~/.bashrc
RUN echo "source /usr/share/bash-completion/completions/git \n" >> ~/.bashrc
SHELL ["/bin/bash", "-c"]
RUN ./python-package.sh


USER root
#install libboost, openmpi, ninja
RUN apt-get install -y libopenmpi-dev liblapack-dev libblas-dev libboost-dev libboost-mpi-dev libboost-serialization-dev libboost-filesystem-dev libboost-system-dev ninja-build

# setting the locale to UTF-8
RUN apt-get update && apt-get install -y locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# setting for ctrl + r command (easier to search history)
RUN apt-get install -y hstr 
USER ${USERNAME}
RUN hstr --show-configuration >> ~/.bashrc


#install ALPSCore and libconfig
USER root
RUN sudo apt-get install -y libhdf5-dev=1.10.7+repack-4ubuntu2 libeigen3-dev
COPY install-libconfig.sh install-libconfig.sh
COPY install-alpscore.sh install-alpscore.sh
RUN ./install-libconfig.sh
RUN ./install-alpscore.sh

# RUN rm -r ALPSCore
# RUN rm -r libconfig


#install libconfig
# ENTRYPOINT ["/bin/bash", "/install-libconfig.sh"]

