version: '3.4'

# volumes:
#   worm_data:

services:
  main:
    container_name: worms_gpu_torch 
    image: kei0709/cuda12.1:latest 
    # image: nvidia/cuda:12.1.1-runtime-ubuntu22.04
    volumes:
      - ..:/home/user/project
      - type: bind
        source: ~/.ssh
        target: /home/user/.ssh
        read_only: true
    tty: true
    ports:
      - 2222:0022
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    working_dir: /home/user/project
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
