version: '3.4'

services:
  worm:
    image: worm_cpp
    container_name: worms
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VARIANT: ubuntu-20.04
    volumes:
      - ../:/home/keisuke/worms:delegated
      - type: bind
        source: ~/.ssh
        target: /home/keisuke/.ssh
        read_only: true
      - type: bind
        source: ~/.gitconfig
        target: /etc/gitconfig
        read_only: true
    ports:
      - "8887:8888"
    # cap_add: 
    #   - SYS_PTRACE
    privileged: true
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: /home/keisuke/worms