version: '3.4'

services:
  main:
    container_name: worms
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VARIANT: ubuntu-22.04
        USERNAME: user
        GROUPNAME: user

    volumes:
      - ../:/home/user/project:consistent
      - type: bind
        source: ~/.ssh
        target: /home/user/.ssh
        read_only: true
      - type: bind
        source: ~/.gitconfig
        target: /etc/gitconfig
        read_only: true
    ports:
      - "8887:8888" #set by yourself
    cap_add: 
      - SYS_PTRACE
    privileged: true
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: /home/user/project