version: '3.4'

services:
  main:
    container_name: worms
    image: kei0709/ubuntu22.04-cpp:amd64
    # build: .
    command: sleep infinity
      # context: .
      # dockerfile: ./Dockerfile
      # args:
      #   VARIANT: ubuntu-22.04
      #   USERNAME: user
      #   GROUPNAME: user
    volumes:
      - source: ../
        target: /home/project
        type: bind
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
      - type: bind
        source: ~/.gitconfig
        target: /etc/gitconfig
    # ports:
      # - "8884:8888" #set by yourself
    cap_add: 
      - SYS_PTRACE
    privileged: true
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: /home/project