# https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/cpp/.devcontainer/base.Dockerfile

FROM ubuntu:22.04 as base
RUN echo "I'm $TARGETARCH"
ARG ARCH=amd64
# RUN echo "I'm building for $TARGETARCH"
# setup non-root user. If you use remote-container, you don't need to adjust this UID.
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN echo "root:root" | chpasswd
RUN echo "$USERNAME:$USERNAME" | chpasswd
# change time-zone
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# change terminal colors
COPY terminal-colors-branch.sh /tmp/
RUN cat /tmp/terminal-colors-branch.sh >> ~/.bashrc

RUN apt-get update -y && apt-get -y install git vim software-properties-common htop cmake openssh-server sudo

RUN adduser $USERNAME sudo

# n* install python 3.9
ARG PY_VERSION="3.9"
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get -y install python${PY_VERSION}-distutils python${PY_VERSION}-dev python${PY_VERSION} 
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PY_VERSION} 1 && update-alternatives --install /usr/bin/python python /usr/bin/python${PY_VERSION} 1 && \
    apt-get -y install python3-pip

# n* install c++
RUN apt-get update -y && apt-get -y install htop build-essential cmake clang libssl-dev vim openssh-server cmake-curses-gui git curl gdb

# n* install boost for c++
RUN apt-get -y install libboost-dev

# # n* git setup
# RUN git config --global --add safe.directory /home/${USERNAME}/project
RUN git config --global core.autocrlf input

USER $USERNAME

# change terminal colors
RUN cat /tmp/terminal-colors-branch.sh >> ~/.bashrc

WORKDIR /home/${USERNAME}
ARG CONDA_VER=latest

# x86
FROM base as base-amd64
ARG OS_TYPE=x86_64

# aarch64
FROM base as base-arm64
ARG OS_TYPE=aarch64

FROM base-${TARGETARCH} as target
# FROM base-${ARCH} as target


# install conda
ARG CONDA=Miniconda3-${CONDA_VER}-Linux-${OS_TYPE}.sh
RUN wget -P /home/${USERNAME} \
    http://repo.continuum.io/miniconda/${CONDA} \
    && mkdir /home/${USERNAME}/.conda \
    && bash ${CONDA} -b\
    # && ./home/${USERNAME}/anaconda3/bin/conda init
    && rm -f ${CONDA}
ENV PATH=/home/${USERNAME}/miniconda3/bin:$PATH
ENV PATH=/home/${USERNAME}/miniconda3/condabin:$PATH
RUN conda init 
RUN conda update -y conda

WORKDIR /home/${USERNAME}/project
