version: '3.4'

volumes:
  worm_data:

services:
  main:
    container_name: worms_gpu
    # env_file: 
    #   - .env
    # environment:
    #   DOCKER_BUILDKIT: 1
    #   COMPOSE_DOCKER_CLI_BUILD: 1
    # image: sonoisa/deep-learning-coding:pytorch1.12.0_tensorflow2.9.1
    # image: ubuntu:jammy-20221101
    image: kei0709/ubuntu22.04-cpp-gpu:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    volumes:
      # - worm_data:/home/user/project
      - ..:/home/user/project
      - type: bind
        source: ~/.ssh
        target: /home/user/.ssh
        read_only: true
      # - type: bind
      #   source: ~/.gitconfig
      #   target: /home/user/.gitconfig
      #   read_only: true
    # ports:
    #   - "8881:8888" #set by yourself
    cap_add: 
      - SYS_PTRACE
    privileged: true
    security_opt: 
      - seccomp:unconfined
    stdin_open: true
    tty: true
    working_dir: /home/user/project
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
